### ISSUE TITLE
Android 12 extension not working on latest Android 12 build.

### ISSUE THREAD

**Issue by Swilla66** [kdrag0n/android12-extensions#10]
Hello dear developer @kdrag0n .
I love this module. But the latest build of android 12 I installed today doesn't recognise my Lsposed so someone hinted that it wasn't working for the latest a12 build.

So I suggest you make an upgrade pleeeeaaaasee.
Thanks and stay blessed. ✌🏽💙

**Comment by kdrag0n** [comment]
A version with support for stable Android 12 is already available here: https://kdrag0n.dev/patreon/android12-extensions/v9.0.0
