### ISSUE TITLE
Features not working properly

### ISSUE THREAD

**Issue by ab3lkaizen** [kdrag0n/android12-extensions#16]
Hey,

the launcher section of the module isn't working properly for me. I mean under that, for example the "On-device search" option is working, but cannot be turned off just with disabling the Xposed module from the Pixel Launcher. And just for another example, the "New Live Space" feature isn't working for some reason, I'm not noticing a difference between the animations as well.
I'm using a joyeuse device, with the latest official Pixel Experience.

The module is awesome by the way, thank you for sharing it with us, I have no complainments, there's a chance that I screwed up something since there isn't any issue submitted with this problem by someone else.
I haven't tested the module with another rom, maybe that's the problem.

Thank you for answering!

**Comment by kdrag0n** [comment]
"New Live Space" is already enabled by default on stable Android 12. On-device search is a bit of a special case, so toggling it both ways shouldn't be expected to take effect in all cases (wiping the launcher's data might help, but you'll lose your home screen layout). The difference between the app open/close animations is relatively subtle, and some people have trouble seeing it at all, so please get a screen recording for that.
