### ISSUE TITLE
Transfer of Tweaks

### ISSUE THREAD

**Issue by Amorphous404** [kdrag0n/android12-extensions#21]
Hey, @kdrag0n can android 12 extension tweak be transferred (expect the monet themeing tweaks) to AOSP Mods as it already have some other feature and this mod doesn't work on A12+ and you'll no longer ne maintaining,

I use your repainter app, but miss the tweaks preset in extension mod

**Comment by Amorphous404** [comment]
https://github.com/siavash79/AOSPMods

**Comment by kdrag0n** [comment]
Android 12 Extensions is open source, so anyone is already free to use it as a reference for features.
