### ISSUE TITLE
The Circle Icons overlay is in the wrong path

### ISSUE THREAD

**Issue by TheBeast0403** [kdrag0n/android12-extensions#5]
On the Android 12 Beta 4 GSI (Build Number SPB4.210715.014) the icon overlay is meant to be in `/system/product/overlay` however your magisk module attempts to put it in `/system/overlay` which does not exist. Manually editing the folders inside the zip according to the folder structure present on my phone has fixed the problem.

Edit: the circle icon theme seems to work in Launchair 11 alpha 6.1, doesn't seem to work in Quickstep or the settings app

**Comment by kdrag0n** [comment]
Does it show up if you run `cmd overlay list`? It used to be in `/system/product/overlay`, but I moved it to `/system/overlay` in order to fix bootloops on some unofficial semi-GSI ports of the Pixel beta builds.

**Comment by TheBeast0403** [comment]
Yeah it shows up as `com.android.theme.icon.circle` but I'm using the my edited one (i.e. the one with the overlay in `/system/product/overlay`)

**Comment by kdrag0n** [comment]
Can you test it with the default `/system/overlay` path? It should work as far as I know, but I don't currently have an AOSP GSI installation to test it.

**Comment by TheBeast0403** [comment]
Switched back to your version. The overlay no longer shows when running the command, however for some reason the circle icons stay in Lawnchair.

**Comment by TheBeast0403** [comment]
Just did a fresh install of Android 12 Beta 4 (since the Beta 5 GSI doesn't seem to boot on my phone) and it turns out that Quickstep does in fact have circle icons now (but it only worked after toggling the option twice)

I used the edited module again since the overlay doesn't seem to be working in your version

**Comment by kdrag0n** [comment]
Fixed in [v8.0.0](https://kdrag0n.dev/patreon/android12-extensions/v8.0.0). Thanks for the details!
