### ISSUE TITLE
LSPosed not found - Pixel 3a

### ISSUE THREAD

**Issue by galaxyentity904** [kdrag0n/android12-extensions#8]
![Screenshot_20211015-012202.png](https://user-images.githubusercontent.com/77765105/137448756-4c6cba20-b02b-4f6a-b480-85e863bfeb64.png)

![Screenshot_20211015-012519.png](https://user-images.githubusercontent.com/77765105/137448782-4ff299a9-835a-44d3-ba18-753239c37a19.png)

LSPosed is not detected even though it's installed. Android 12 Extensions does have superuser rights, and the dependencies seemed to install properly.

**Comment by galaxyentity904** [comment]
Update- I tried version 1.5.1 of lsposed too and it does not seem to work

**Comment by kdrag0n** [comment]
Fixed in [v9.0.0](https://kdrag0n.dev/patreon/android12-extensions/v9.0.0?utm_source=github).

**Comment by palexdev** [comment]
I have the same issue on v9.0.0
![Screenshot_20211111-140921_MMSettings](https://user-images.githubusercontent.com/16880178/141303823-747b0362-a35c-49ed-8210-e80d1c54210f.png)
![Screenshot_20211111-140941_MMSettings~2](https://user-images.githubusercontent.com/16880178/141303833-a612d15a-ec27-4ba6-9483-bbb529c886d6.png)
![Screenshot_20211111-140948_Android 12 Extensions](https://user-images.githubusercontent.com/16880178/141303842-beeb3e11-5198-4e98-8066-324e4ee9c0a6.png)

**Comment by kdrag0n** [comment]
@palexdev Try disabling and re-enabling the module in LSPosed Manager.

**Comment by palexdev** [comment]
> @palexdev Try disabling and re-enabling the module in LSPosed Manager.

@kdrag0n Ah yes sorry, I didn't know the module needed to be enabled, I thought it was automatic

Anyway I had another severe issue, on reboot my device UI kept flashing not responding to any input
I had to remove all magisk modules with adb to recover

**Comment by kdrag0n** [comment]
> > @palexdev Try disabling and re-enabling the module in LSPosed Manager.
> 
> @kdrag0n Ah yes sorry, I didn't know the module needed to be enabled, I thought it was automatic
> 
> Anyway I had another severe issue, on reboot my device UI kept flashing not responding to any input
> I had to remove all magisk modules with adb to recover 

It should be fixed with this version: https://patreon.kdrag0n.dev/exclusive/android12-extensions-v9.0.0-aospmonetfix.zip
